site_name: Курс "Основы алгоритмического программирования"


theme:
  name: 'material'
  language: 'ru'
  
plugins: []
#extra:
#  search:
#    language: 'en, ru'
  
nav:
    - Главная: index.md
    - Курс:
        - Установка программного обеспечения: course/prep/install.md
        - 1. Основы алгоритмизации и программирования:
            - 1.1. Алгоритм и блок-схема: course/p1/t1.md
            - 1.2. Переменные и константы: course/p1/t2.md
            - 1.2. Основные операции с переменными: course/p1/t3.md
    - Задачи:
        - Тест: tasks/exam.md
    - Технические статьи:
        - Шпаргалка по Markdown: tech/cheatsheet.md
        - Выкладывание на Github pages: tech/deploy.md
        - Семантический конспект: tech/semantic.md
        - Процедурная модель: tech/procedural.md
        - Модель умений: tech/skills.md

markdown_extensions:
    - tables
    - admonition
    - attr_list
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.mark
    - pymdownx.caret
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences:
        custom_fences:
           - name: mermaid
             class: mermaid
             format: !!python/name:pymdownx.superfences.fence_div_format
             
extra_css:
  - mermaid/mermaid.css
  - katex/katex.min.css
extra_javascript:
  - mermaid/mermaid.min.js
  - katex/mkdocs_load.js
  - katex/katex.min.js
    